version: "3.4"
name: contacts
services:
  db:
    build:
      context: ./db
    container_name: contacts-db-dev
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysql", "-uuser", "-ppassword", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - networks1
  backend:
    image: contacts
    container_name: contacts-api
    ports:
      - "8080:8080"
    depends_on:
      - db:
        condition: service_healthy
    networks:
      - networks1
networks:
  network1:
    driver: bridge


