version: "3.9"
name: contacts

services:
  db:
    build:
      context: ./db
    container_name: contacts-db-dev
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DB: contactsdb
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysql", "ping", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 6
