version: "3.4"
name: contacts
services:
  db:
  image: mariadb:11.3.2
  container_name: contacts-db-dev
  environment:
    MYSQL_USER: 'user'
    MYSQL_PASSWORD: 'password'
    MYSQL_DB: 'contactsdb'
    MYSQL_PORT: 3306
    MYSQL_ROOT_PASSWORD: 'rootpassword'
  ports:
    - "3306:3306"
  volumes:
    - ./db:/docker-entrypoint-initdb.d
    
  backend:
    image: contacts
    container_name: contacts-api
    ports: 
      - "8080:8080"


